version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/prod/frontend/Dockerfile
    ports:
      - 3000:80

  backend:
    build:
      context: .
      dockerfile: ./docker/prod/backend/Dockerfile
    ports:
      - 8000:8000

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/dev/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./environment/sql:/work/sql:ro
    working_dir: /work

volumes:
  db-data:
