version: '3'

services:
  backend:
    build: ./docker/dev/backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/go/src/app:cached
    tty: true
    working_dir: /go/src/app/todo

  db:
    image: mysql:8
    # M1 Mac用
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      TZ: 'Asia/Tokyo'
    command: mysqld
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/dev/db/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./environment/sql:/work/sql:ro
    working_dir: /work

volumes:
  db-data:
